### ISSUE TITLE
Issues during go get

### ISSUE THREAD

**Issue by fdruillennec** [jmhodges/gocld3#1]
Hi,
I am trying to use gocld3 but I have got some issues during the install.
Is there any pre-requisities to do before getting the project?

**What version of Go are you using (go version)?**
`go version go1.9.3 darwin/amd64`

**What operating system and processor architecture are you using (go env)?**
`macOS 10.13.6`

**Version of protoc (protoc --version)?**
`libprotoc 2.6.1`

**What did you do?**
`go get github.com/jmhodges/gocld3/cld3`

**What did you expect to see?**
A successful install

**What did you see instead?**
```
$ go get github.com/jmhodges/gocld3/cld3
# github.com/jmhodges/gocld3/cld3
In file included from cld3.cc:3:
In file included from gocld3/cld3/nnet_language_identifier.h:22:
In file included from gocld3/cld3/embedding_feature_extractor.h:23:
In file included from gocld3/cld3/feature_extractor.h:45:
gocld3/cld3/feature_extractor.pb.h:12:2: error: This file was generated by a newer version of protoc which is
gocld3/cld3/feature_extractor.pb.h:13:2: error: incompatible with your Protocol Buffer headers.  Please update
gocld3/cld3/feature_extractor.pb.h:14:2: error: your headers.
gocld3/cld3/feature_extractor.pb.h:23:10: fatal error: 'google/protobuf/arena.h' file not found
```

**Comment by jmhodges** [comment]
What version of protobuf headers do you have installed?

**Comment by jmhodges** [comment]
Ah, yep, I can repro. Regening the code with a newer protobuf fixes that issue. Run that with `go get -u` and you'll get the fixed code!

**Comment by jmhodges** [comment]
(Also, sorry for missing the version of libprotobuf that you included!)

**Comment by fdruillennec** [comment]
Thanks! It worked well.
